# Generated by Django 3.1.7 on 2021-03-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
